"""
Study content and quiz bank for Texas P&C Insurance Exam.
Content is educational and based on publicly available exam outlines and Texas statutes.
"""

MODULES = [
    {
        "id": "foundations",
        "title": "Core Insurance Concepts & Terminology",
        "description": "Risk, peril, hazard, indemnity, ACV vs RC, coinsurance, negligence, policy structure (DICE).",
        "priority": "high",
        "estimated_minutes": 45,
        "content": {
            "key_concepts": [
                "Pure risk vs Speculative risk",
                "Peril (cause of loss) vs Hazard (increases chance/severity)",
                "Insurable interest must exist at time of loss (property) or inception (life)",
                "Indemnity: restore to pre-loss condition, no profit",
                "Actual Cash Value (ACV) = Replacement Cost - Depreciation",
                "Replacement Cost: no deduction for depreciation",
                "Coinsurance: insured must carry adequate coverage or face penalty",
                "Proximate cause: unbroken chain from peril to loss",
                "Elements of negligence: Duty, Breach, Proximate Cause, Damages",
                "Policy structure: Declarations, Insuring Agreement, Conditions, Exclusions",
            ],
            "study_notes": "Master these definitions. They appear in almost every section of the exam.",
        },
    },
    {
        "id": "property-policies",
        "title": "Types of Property Policies",
        "description": "Homeowners (HO-2/3/4/5/6/8), Dwelling (DP-1/2/3), Commercial Property, Inland Marine, Flood, TWIA & FAIR Plan.",
        "priority": "high",
        "estimated_minutes": 60,
        "content": {
            "key_concepts": [
                "HO-3 is the most common homeowners form (open peril on dwelling, named on contents)",
                "HO-4 = Renters, HO-6 = Condo unit owners",
                "DP forms generally lack liability coverage that HO provides",
                "Named perils vs Open perils",
                "TWIA: Texas Windstorm Insurance Association – coastal wind & hail only",
                "FAIR Plan (TFPA): last-resort fire and related property coverage statewide",
                "TWIA and FAIR Plan are residual markets – markets of last resort",
                "NFIP Flood insurance has a waiting period (typically 30 days)",
                "Coinsurance penalty formula: (Did / Should) x Loss - Deductible",
            ],
            "study_notes": "Distinguish TWIA (wind/hail coastal) from FAIR Plan (broader perils, high-risk properties). This is heavily tested.",
        },
    },
    {
        "id": "casualty-policies",
        "title": "Types of Casualty Policies",
        "description": "Personal & Business Auto, CGL, Workers’ Comp (Texas nonsubscriber), Umbrella, Bonds.",
        "priority": "high",
        "estimated_minutes": 60,
        "content": {
            "key_concepts": [
                "Texas minimum auto liability: 30/60/25 ($30k BI per person / $60k BI per accident / $25k PD)",
                "PAP Parts: A=Liability, B=Med Pay, C=UM/UIM, D=Physical Damage",
                "UM/UIM and PIP must be offered; can be rejected in writing",
                "Texas is unique: private employers may opt out of Workers’ Comp (nonsubscribers)",
                "Nonsubscribers lose common-law defenses (contributory negligence, assumption of risk, fellow servant)",
                "CGL Coverages: A (BI/PD), B (Personal & Advertising Injury), C (Medical Payments)",
                "Occurrence vs Claims-Made triggers",
                "Surety bond parties: Principal, Obligee, Surety",
            ],
            "study_notes": "30/60/25 and the nonsubscriber rule are pure Texas gold. Memorize them cold.",
        },
    },
    {
        "id": "texas-statutes",
        "title": "Texas Statutes, Rules & Regulations",
        "description": "Licensing, unfair trade practices, CE, TPCIGA, residual markets, claims rules.",
        "priority": "high",
        "estimated_minutes": 50,
        "content": {
            "key_concepts": [
                "Commissioner of Insurance is appointed by the Governor",
                "Continuing Education: 24 hours every 2 years, including 3 hours ethics",
                "At least half of CE must be classroom or classroom-equivalent",
                "Unfair practices: misrepresentation, rebating, twisting, defamation, unfair discrimination",
                "TPCIGA (Texas Property & Casualty Insurance Guaranty Association) protects against insolvent insurers",
                "Typical TPCIGA limit: $300,000 per claim or policy limits, whichever is less",
                "File-and-use rate regulation in Texas",
                "Temporary license available (requires sponsorship + 40 hours education)",
            ],
            "study_notes": "The 30 Texas-specific questions often decide pass/fail. Drill this module daily.",
        },
    },
    {
        "id": "policy-provisions",
        "title": "Policy Provisions & Contract Law",
        "description": "Cancellation, nonrenewal, subrogation, other insurance, duties after loss, contract characteristics.",
        "priority": "medium",
        "estimated_minutes": 40,
        "content": {
            "key_concepts": [
                "Insurance contracts are contracts of adhesion, aleatory, unilateral, conditional",
                "Representations vs Warranties",
                "Waiver and Estoppel",
                "Subrogation allows insurer to pursue third parties after paying claim",
                "Other Insurance clauses (pro-rata, excess, primary)",
                "Texas has specific notice requirements for cancellation and nonrenewal of personal lines",
            ],
            "study_notes": "Focus on how Texas rules modify standard ISO provisions for cancellation/nonrenewal.",
        },
    },
]

TEXAS_CHEATSHEET = {
    "title": "Texas P&C High-Yield Cheat Sheet",
    "auto_limits": "30/60/25 – $30,000 BI per person / $60,000 BI per accident / $25,000 property damage",
    "workers_comp": "OPTIONAL for private employers. Nonsubscribers forfeit common-law defenses.",
    "twia": "Texas Windstorm Insurance Association – last-resort wind & hail in designated coastal catastrophe area.",
    "fair_plan": "Texas FAIR Plan Association – last-resort residential property (fire etc.) for high-risk properties statewide. Does not cover wind/hail in TWIA area.",
    "ce_requirements": "24 hours every 2 years, including 3 ethics. At least 50% classroom or equivalent.",
    "tpciga": "Guaranty association – generally $300,000 per claim or policy limits, whichever less.",
    "rate_regulation": "File-and-use",
    "commissioner": "Appointed by the Governor with Senate confirmation",
    "um_uim_pip": "Must be offered; can be rejected in writing by the insured",
    "exam_format": "145 questions (130 scored), 150 minutes, 70% to pass, Pearson VUE test centers only",
}

QUIZ_BANK = {
    "foundations": [
        {
            "id": "f1",
            "question": "What is the primary purpose of the principle of indemnity?",
            "options": ["A. To allow the insured to profit from a loss", "B. To restore the insured to the approximate financial condition before the loss", "C. To provide unlimited coverage", "D. To transfer all risk to the government"],
            "correct": "B",
            "explanation": "Indemnity aims to make the insured whole again without allowing profit from the loss.",
        },
        {
            "id": "f2",
            "question": "Actual Cash Value (ACV) is best defined as:",
            "options": ["A. Replacement cost without depreciation", "B. Market value only", "C. Replacement cost minus depreciation", "D. Original purchase price"],
            "correct": "C",
            "explanation": "ACV = Replacement Cost − Depreciation.",
        },
        {
            "id": "f3",
            "question": "Which of the following is an element of negligence?",
            "options": ["A. Intentional act", "B. Duty owed", "C. Strict liability", "D. Absolute liability"],
            "correct": "B",
            "explanation": "The four elements are Duty, Breach, Proximate Cause, and Damages.",
        },
        {
            "id": "f4",
            "question": "A hazard is best described as:",
            "options": ["A. The cause of a loss", "B. A condition that increases the chance or severity of a loss", "C. The financial loss itself", "D. A type of insurance policy"],
            "correct": "B",
            "explanation": "Peril is the cause; hazard increases frequency or severity.",
        },
        {
            "id": "f5",
            "question": "In a property insurance policy, insurable interest must exist:",
            "options": ["A. Only at policy inception", "B. At the time of the loss", "C. Only when the claim is paid", "D. Never – it is not required"],
            "correct": "B",
            "explanation": "For property insurance, insurable interest must exist at the time of the loss.",
        },
    ],
    "property-policies": [
        {
            "id": "p1",
            "question": "What does TWIA primarily provide?",
            "options": ["A. Flood insurance statewide", "B. Wind and hail coverage in designated coastal areas", "C. Auto liability coverage", "D. Workers’ compensation"],
            "correct": "B",
            "explanation": "TWIA is the residual market for windstorm and hail in the Texas coastal catastrophe area.",
        },
        {
            "id": "p2",
            "question": "The Texas FAIR Plan is best described as:",
            "options": ["A. A coastal windstorm pool", "B. A last-resort market for residential property insurance", "C. A mandatory workers’ comp program", "D. An auto assigned-risk plan"],
            "correct": "B",
            "explanation": "FAIR Plan provides property coverage (primarily fire and related perils) when the voluntary market declines the risk.",
        },
        {
            "id": "p3",
            "question": "Which homeowners form is most commonly written and provides open-peril coverage on the dwelling?",
            "options": ["A. HO-2", "B. HO-3", "C. HO-4", "D. HO-8"],
            "correct": "B",
            "explanation": "HO-3 is the standard special form used for most owner-occupied homes.",
        },
        {
            "id": "p4",
            "question": "HO-4 is designed for:",
            "options": ["A. Condominium unit owners", "B. Renters / tenants", "C. Historic homes", "D. Mobile homes only"],
            "correct": "B",
            "explanation": "HO-4 is the renters policy; HO-6 is for condo unit owners.",
        },
        {
            "id": "p5",
            "question": "In the coinsurance formula, if an insured carries less than the required amount of insurance, the claim payment is:",
            "options": ["A. Always the full loss", "B. Reduced proportionally", "C. Denied entirely", "D. Paid at replacement cost automatically"],
            "correct": "B",
            "explanation": "The insured becomes a co-insurer and shares in the loss proportionally.",
        },
    ],
    "casualty-policies": [
        {
            "id": "c1",
            "question": "What are the minimum auto liability limits required in Texas?",
            "options": ["A. 25/50/25", "B. 30/60/25", "C. 50/100/50", "D. 15/30/10"],
            "correct": "B",
            "explanation": "Texas requires 30/60/25.",
        },
        {
            "id": "c2",
            "question": "In Texas, private employers may:",
            "options": ["A. Be required by law to carry workers’ compensation", "B. Opt out of workers’ compensation and become nonsubscribers", "C. Only purchase workers’ comp through a state fund", "D. Never be sued by injured employees"],
            "correct": "B",
            "explanation": "Texas is unique in allowing private employers to opt out (nonsubscribers), but they lose important common-law defenses.",
        },
        {
            "id": "c3",
            "question": "Which Personal Auto Policy part provides coverage for bodily injury and property damage the insured causes to others?",
            "options": ["A. Part B", "B. Part C", "C. Part A", "D. Part D"],
            "correct": "C",
            "explanation": "Part A is Liability coverage.",
        },
        {
            "id": "c4",
            "question": "Uninsured/Underinsured Motorist coverage in Texas:",
            "options": ["A. Is automatic and cannot be rejected", "B. Must be offered but can be rejected in writing", "C. Is only available through TAIPA", "D. Covers only property damage"],
            "correct": "B",
            "explanation": "UM/UIM (and PIP) must be offered; the insured may reject them in writing.",
        },
        {
            "id": "c5",
            "question": "A nonsubscriber in Texas workers’ compensation:",
            "options": ["A. Retains all common-law defenses", "B. Loses the defenses of contributory negligence, assumption of risk, and fellow-servant rule", "C. Cannot be sued by employees", "D. Is automatically covered by the state"],
            "correct": "B",
            "explanation": "Opting out means forfeiting those traditional employer defenses.",
        },
    ],
    "texas-statutes": [
        {
            "id": "t1",
            "question": "How many hours of continuing education are required every two years for a Texas P&C license?",
            "options": ["A. 12 hours", "B. 20 hours", "C. 24 hours (including 3 ethics)", "D. 30 hours"],
            "correct": "C",
            "explanation": "24 hours total, of which at least 3 must be ethics.",
        },
        {
            "id": "t2",
            "question": "The Texas Property and Casualty Insurance Guaranty Association (TPCIGA) typically pays up to:",
            "options": ["A. $100,000 per claim", "B. $300,000 per claim or policy limits, whichever is less", "C. Unlimited amounts", "D. Only return of premium"],
            "correct": "B",
            "explanation": "Standard TPCIGA limit is $300,000 per claim or the policy limits, whichever is less.",
        },
        {
            "id": "t3",
            "question": "Who appoints the Texas Commissioner of Insurance?",
            "options": ["A. The Legislature", "B. The Governor (with Senate confirmation)", "C. Popular election", "D. The insurance industry"],
            "correct": "B",
            "explanation": "The Commissioner is appointed by the Governor with the advice and consent of the Senate.",
        },
        {
            "id": "t4",
            "question": "Which of the following is generally considered an unfair trade practice?",
            "options": ["A. Charging different rates based on risk", "B. Rebating premiums to induce a sale", "C. Offering multiple policy options", "D. Explaining coverage clearly"],
            "correct": "B",
            "explanation": "Rebating is a prohibited unfair trade practice.",
        },
        {
            "id": "t5",
            "question": "Texas uses which system for rate regulation of most property and casualty lines?",
            "options": ["A. Prior approval", "B. File-and-use", "C. Open competition with no filing", "D. State-set rates only"],
            "correct": "B",
            "explanation": "Texas primarily uses a file-and-use system.",
        },
    ],
    "general": [
        {
            "id": "g1",
            "question": "The Texas minimum auto liability limits are commonly written as:",
            "options": ["A. 20/40/15", "B. 30/60/25", "C. 50/100/25", "D. 25/50/25"],
            "correct": "B",
            "explanation": "30/60/25 is the statutory minimum in Texas.",
        },
    ],
}
